collections:
  - name: ansible.utils
    version: ">=2.0.0"
  - name: community.general
    version: ">=2.0.0"

roles:
  - name: markcallen.novnc_desktop
    src: https://github.com/markcallen/novnc-desktop
    scm: git
    version: v0.1.5
