package provision

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/orchael/ai-desktops/internal/config"
)

const (
	// AIAgentBridgeVersion must match ai_agent_bridge_version in packer/variables.pkrvars.hcl.
	AIAgentBridgeVersion  = "v0.9.1"
	DefaultNoVNCHTTPPort  = 8080
	DefaultNoVNCHTTPSPort = 8443
)

// BootstrapConfig holds the parameters for rendering the cloud-init user-data.
type BootstrapConfig struct {
	DesktopID            string
	Hostname             string // FQDN used for certbot cert and novnc-desktop cert path
	GitHubOwner          string
	Repos                []string
	WorkspacePath        string
	BridgePort           int
	NoVNCHTTPPort        int
	NoVNCHTTPSPort       int
	CertbotEmail         string
	GitHubSecretPath     string   // AWS Secrets Manager path: /ai-desktops/<owner>/github
	AgentSecretPath      string   // AWS Secrets Manager path: /ai-desktops/<owner>/agents
	DesktopSecretPaths   []string // additional AWS Secrets Manager paths whose JSON keys become ubuntu env vars
	TailscaleNetwork     string   // optional Tailscale tailnet/network name
	TailscaleSecretPath  string   // AWS Secrets Manager path containing {"TS_AUTHKEY":"..."}
	StepCAServerDNS      string   // optional step-ca DNS name
	StepCAFingerprint    string   // optional step-ca root fingerprint for non-interactive bootstrap
	StepCAProvisioner    string   // step-ca provisioner used for bridge host certs
	StepCASecretPath     string   // AWS Secrets Manager path containing {"STEP_CA_PROVISIONER_PASSWORD":"..."}
	StepCAClients        []StepCAClient
	AWSRegion            string
	Environment          string
	PackagesPreInstalled bool
	SSHPublicKey         string // ed25519/RSA public key injected into ubuntu's authorized_keys
	GitUserName          string // git config user.name written to ubuntu's global git config
	GitUserEmail         string // git config user.email written to ubuntu's global git config
	// SwapSizeGB is the size of the swap file to create in GiB.
	// 0 means no swap file is created.
	SwapSizeGB int
	// AVDs lists Android Virtual Devices to create at boot.
	// Requires the Android SDK to be pre-installed in the AMI (ANDROID_HOME=/opt/android-sdk).
	// Empty means no AVDs are created.
	AVDs []config.AVDConfig
}

type StepCAClient struct {
	Issuer    string
	PublicKey string
	Required  bool
}

const cloudInitTemplate = `#cloud-config
# ai-desktops bootstrap — desktop {{ .DesktopID }}
# Generated by ai-desktops CLI
{{- if .SSHPublicKey}}

ssh_authorized_keys:
  - {{ .SSHPublicKey }}
{{- end}}

{{- if not .PackagesPreInstalled}}
package_update: true
package_upgrade: false

packages:
  - git
  - docker.io
  - tmux
  - curl
  - wget
  - unzip
  - ca-certificates
  - apt-transport-https
  - gnupg
  - lsb-release
  - software-properties-common
  - snapd
  - awscli
  - certbot
  - python3-certbot-dns-route53
  - ansible
  - gh
{{- end}}

runcmd:
  # --- system setup ---
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

{{- if not .PackagesPreInstalled}}
  # --- nvim (via snap) ---
  - snap install nvim --classic
{{- end}}

  # --- workspace ---
  - mkdir -p {{ .WorkspacePath }}
  - chown ubuntu:ubuntu {{ .WorkspacePath }}

  # --- ai-desktops runtime directory ---
  - mkdir -p /opt/ai-desktops
  - chown ubuntu:ubuntu /opt/ai-desktops
  - |
    cat >/opt/ai-desktops/apt-with-lock <<'SH'
    #!/bin/sh
    set -e
    timeout="${APT_LOCK_TIMEOUT:-600}"
    deadline=$(( $(date +%s) + timeout ))
    locks="/var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/cache/apt/archives/lock /var/lib/apt/lists/lock"
    if ! command -v fuser >/dev/null 2>&1; then
      echo "ERROR: fuser is required to wait for apt/dpkg locks" >&2
      exit 1
    fi
    while fuser $locks >/dev/null 2>&1; do
      if [ "$(date +%s)" -ge "$deadline" ]; then
        echo "ERROR: timed out waiting for apt/dpkg locks" >&2
        fuser -v $locks >&2 || true
        exit 1
      fi
      echo "Waiting for apt/dpkg lock..."
      sleep 5
    done
    if [ "$1" = "apt-get" ]; then
      shift
      exec apt-get -o DPkg::Lock::Timeout="$timeout" "$@"
    fi
    exec "$@"
    SH
    chmod 0755 /opt/ai-desktops/apt-with-lock

  # --- ensure ai-agent-bridge/bridgectl package version matches the CLI ---
  - |
    (
    set -e
    EXPECTED_BRIDGE_VERSION="{{ .BridgePackageVersion }}"
    INSTALLED_BRIDGE_VERSION=$(dpkg-query -W -f='${Version}' ai-agent-bridge 2>/dev/null || true)
    if [ "$INSTALLED_BRIDGE_VERSION" = "$EXPECTED_BRIDGE_VERSION" ]; then
      echo "ai-agent-bridge version $EXPECTED_BRIDGE_VERSION already installed"
      exit 0
    fi

    echo "Installing ai-agent-bridge $EXPECTED_BRIDGE_VERSION (found: ${INSTALLED_BRIDGE_VERSION:-missing})"
    /opt/ai-desktops/apt-with-lock apt-get update
    /opt/ai-desktops/apt-with-lock apt-get install -y --no-install-recommends curl gpg ca-certificates
    install -d -m 0755 /etc/apt/keyrings
    if [ ! -f /etc/apt/keyrings/ai-agent-bridge.gpg ]; then
      BRIDGE_KEY_ASC=$(mktemp)
      trap 'rm -f "$BRIDGE_KEY_ASC"' EXIT
      curl -fsSL https://markcallen.github.io/ai-agent-bridge/apt/ai-agent-bridge-archive-keyring.asc -o "$BRIDGE_KEY_ASC"
      gpg --dearmor -o /etc/apt/keyrings/ai-agent-bridge.gpg "$BRIDGE_KEY_ASC"
      rm -f "$BRIDGE_KEY_ASC"
      trap - EXIT
      chmod 0644 /etc/apt/keyrings/ai-agent-bridge.gpg
    fi
    ARCH=$(dpkg --print-architecture)
    . /etc/os-release
    UBUNTU_CODENAME="${VERSION_CODENAME:-noble}"
    printf 'deb [arch=%s signed-by=/etc/apt/keyrings/ai-agent-bridge.gpg] https://markcallen.github.io/ai-agent-bridge/apt %s main\n' \
      "$ARCH" "$UBUNTU_CODENAME" > /etc/apt/sources.list.d/ai-agent-bridge.list
    /opt/ai-desktops/apt-with-lock apt-get update
    /opt/ai-desktops/apt-with-lock apt-get install -y --allow-downgrades --no-install-recommends "ai-agent-bridge=${EXPECTED_BRIDGE_VERSION}"
    if [ -x /usr/lib/ai-agent-bridge/install-provider-runtime ]; then
      /usr/lib/ai-agent-bridge/install-provider-runtime || echo "WARNING: install-provider-runtime failed after ai-agent-bridge version correction"
    fi
    INSTALLED_BRIDGE_VERSION=$(dpkg-query -W -f='${Version}' ai-agent-bridge)
    if [ "$INSTALLED_BRIDGE_VERSION" != "$EXPECTED_BRIDGE_VERSION" ]; then
      echo "ERROR: ai-agent-bridge version mismatch after install: expected $EXPECTED_BRIDGE_VERSION, got $INSTALLED_BRIDGE_VERSION" >&2
      exit 1
    fi
    )

{{- if .TailscaleNetwork}}
  # --- Tailscale network attachment ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    TAILSCALE_NETWORK="{{ .TailscaleNetwork }}"
    TAILSCALE_SECRET="{{ .TailscaleSecretPath }}"
    TAILSCALE_HOSTNAME="{{ .DesktopID }}"

    if ! command -v tailscale >/dev/null 2>&1; then
      TAILSCALE_INSTALL=$(mktemp)
      trap 'rm -f "$TAILSCALE_INSTALL"' EXIT
      curl -fsSL https://tailscale.com/install.sh -o "$TAILSCALE_INSTALL"
      sh "$TAILSCALE_INSTALL"
      rm -f "$TAILSCALE_INSTALL"
      trap - EXIT
    fi

    systemctl enable tailscaled
    systemctl start tailscaled

    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$TAILSCALE_SECRET" \
      --query SecretString \
      --output text)
    TS_AUTHKEY=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['TS_AUTHKEY'])")
    unset SECRET_JSON

    tailscale up \
      --auth-key "$TS_AUTHKEY" \
      --hostname "$TAILSCALE_HOSTNAME" \
      --accept-dns=true \
      --ssh=true
    unset TS_AUTHKEY

    for i in $(seq 1 60); do
      if tailscale status --json 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin).get('BackendState',''))" | grep -qx Running; then
        printf 'TAILSCALE_NETWORK="%s"\n' "$TAILSCALE_NETWORK" > /opt/ai-desktops/tailscale.env
        chmod 640 /opt/ai-desktops/tailscale.env
        chgrp ubuntu /opt/ai-desktops/tailscale.env
        exit 0
      fi
      sleep 2
    done
    echo "ERROR: Tailscale did not reach Running state" >&2
    exit 1
    )
{{- end}}

{{- if .StepCAServerDNS}}
  # --- step-ca trust/bootstrap for bridgectl agent server ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    STEP_CA="{{ .StepCAServerDNS }}"
    STEP_CA_FINGERPRINT="{{ .StepCAFingerprint }}"
    STEP_PROVISIONER="{{ .StepCAProvisioner }}"
    STEP_SECRET="{{ .StepCASecretPath }}"
    CERT_DIR="/home/ubuntu/.config/bridgectl/tls"
    CERT_NAME="{{ .DesktopID }}"
    STEP_CA_ROOT="/root/.step/certs/root_ca.crt"
    STEP_CA_API_ROOT="$STEP_CA_ROOT"
    STEP_CA_PERSISTENT_PASSWORD_FILE="/home/ubuntu/.config/bridgectl/step-ca-provisioner-password"

    # The CA often lives on Tailscale, so wait for DNS after optional Tailscale attachment.
    for i in $(seq 1 90); do
      if getent hosts "$STEP_CA" >/dev/null 2>&1; then
        break
      fi
      sleep 2
      if [ "$i" = "90" ]; then
        echo "ERROR: step-ca host $STEP_CA did not resolve" >&2
        exit 1
      fi
    done

    if ! command -v step >/dev/null 2>&1; then
      /opt/ai-desktops/apt-with-lock apt-get update
      /opt/ai-desktops/apt-with-lock apt-get install -y --no-install-recommends curl gpg ca-certificates openssl
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://packages.smallstep.com/keys/apt/repo-signing-key.gpg \
        -o /etc/apt/keyrings/smallstep.asc
      printf '%s\n' \
        'Types: deb' \
        'URIs: https://packages.smallstep.com/stable/debian' \
        'Suites: debs' \
        'Components: main' \
        'Signed-By: /etc/apt/keyrings/smallstep.asc' \
        > /etc/apt/sources.list.d/smallstep.sources
      /opt/ai-desktops/apt-with-lock apt-get update
      /opt/ai-desktops/apt-with-lock apt-get install -y step-cli
    fi
    if ! command -v openssl >/dev/null 2>&1; then
      /opt/ai-desktops/apt-with-lock apt-get update
      /opt/ai-desktops/apt-with-lock apt-get install -y --no-install-recommends openssl
    fi
    if ! python3 -c 'import yaml' >/dev/null 2>&1; then
      /opt/ai-desktops/apt-with-lock apt-get update
      /opt/ai-desktops/apt-with-lock apt-get install -y --no-install-recommends python3-yaml
    fi

    if ! step ca health --ca-url "https://${STEP_CA}" --root "$STEP_CA_ROOT" >/dev/null 2>&1; then
      if [ -n "$STEP_CA_FINGERPRINT" ]; then
        step ca bootstrap --ca-url "https://${STEP_CA}" --fingerprint "$STEP_CA_FINGERPRINT" --install --force
      else
        step ca bootstrap --ca-url "https://${STEP_CA}" --install --force
      fi
    fi
    if ! step ca health --ca-url "https://${STEP_CA}" --root "$STEP_CA_API_ROOT" >/dev/null 2>&1; then
      for ROOT_CANDIDATE in /etc/ssl/certs/ISRG_Root_X1.pem /etc/ssl/certs/ISRG_Root_X2.pem; do
        if [ -f "$ROOT_CANDIDATE" ] && step ca health --ca-url "https://${STEP_CA}" --root "$ROOT_CANDIDATE" >/dev/null 2>&1; then
          STEP_CA_API_ROOT="$ROOT_CANDIDATE"
          break
        fi
      done
    fi
    step ca health --ca-url "https://${STEP_CA}" --root "$STEP_CA_API_ROOT" >/dev/null

    install -d -o ubuntu -g ubuntu -m 700 "$CERT_DIR"
    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$STEP_SECRET" \
      --query SecretString \
      --output text)
    STEP_CA_PROVISIONER_PASSWORD=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['STEP_CA_PROVISIONER_PASSWORD'])")
    unset SECRET_JSON
    install -o ubuntu -g ubuntu -m 600 /dev/null "$STEP_CA_PERSISTENT_PASSWORD_FILE"
    printf '%s\n' "$STEP_CA_PROVISIONER_PASSWORD" > "$STEP_CA_PERSISTENT_PASSWORD_FILE"

    STEP_CA_PASSWORD_FILE=$(mktemp)
    STEP_CA_TOKEN_FILE=$(mktemp)
    STEP_CA_CSR_FILE=$(mktemp)
    STEP_CA_SIGN_REQUEST=$(mktemp)
    STEP_CA_SIGN_RESPONSE=$(mktemp)
    trap 'rm -f "$STEP_CA_PASSWORD_FILE" "$STEP_CA_TOKEN_FILE" "$STEP_CA_CSR_FILE" "$STEP_CA_SIGN_REQUEST" "$STEP_CA_SIGN_RESPONSE"' EXIT
    printf '%s\n' "$STEP_CA_PROVISIONER_PASSWORD" > "$STEP_CA_PASSWORD_FILE"
    chmod 600 "$STEP_CA_PASSWORD_FILE"
    TAILSCALE_DNS_NAME=""
    if command -v tailscale >/dev/null 2>&1; then
      TAILSCALE_DNS_NAME=$(tailscale status --json 2>/dev/null | python3 -c 'import json,sys; print((json.load(sys.stdin).get("Self") or {}).get("DNSName","").rstrip("."))' 2>/dev/null || true)
    fi
    CSR_SANS="DNS:{{ .Hostname }},DNS:${CERT_NAME}"
    if [ -n "$TAILSCALE_DNS_NAME" ]; then
      CSR_SANS="${CSR_SANS},DNS:${TAILSCALE_DNS_NAME}"
      step ca token \
        "$CERT_NAME" \
        --ca-url "https://${STEP_CA}" \
        --root "$STEP_CA_API_ROOT" \
        --provisioner "$STEP_PROVISIONER" \
        --provisioner-password-file "$STEP_CA_PASSWORD_FILE" \
        --san "{{ .Hostname }}" \
        --san "$CERT_NAME" \
        --san "$TAILSCALE_DNS_NAME" \
        > "$STEP_CA_TOKEN_FILE"
    else
      step ca token \
        "$CERT_NAME" \
        --ca-url "https://${STEP_CA}" \
        --root "$STEP_CA_API_ROOT" \
        --provisioner "$STEP_PROVISIONER" \
        --provisioner-password-file "$STEP_CA_PASSWORD_FILE" \
        --san "{{ .Hostname }}" \
        --san "$CERT_NAME" \
        > "$STEP_CA_TOKEN_FILE"
    fi
    openssl req -new \
      -newkey ec \
      -pkeyopt ec_paramgen_curve:P-256 \
      -nodes \
      -keyout "$CERT_DIR/server.key" \
      -out "$STEP_CA_CSR_FILE" \
      -subj "/CN=${CERT_NAME}" \
      -addext "subjectAltName=${CSR_SANS}"
    python3 - "$STEP_CA_CSR_FILE" "$STEP_CA_TOKEN_FILE" "$STEP_CA_SIGN_REQUEST" <<'PY'
    import json
    import sys

    csr_path, token_path, output_path = sys.argv[1:4]
    with open(csr_path, encoding="utf-8") as csr_file:
        csr = csr_file.read()
    with open(token_path, encoding="utf-8") as token_file:
        token = token_file.read().strip()
    with open(output_path, "w", encoding="utf-8") as output_file:
        json.dump({"csr": csr, "ott": token}, output_file)
    PY
    curl -fsSL \
      --cacert "$STEP_CA_API_ROOT" \
      -H 'Content-Type: application/json' \
      --data @"$STEP_CA_SIGN_REQUEST" \
      "https://${STEP_CA}/1.0/sign" \
      > "$STEP_CA_SIGN_RESPONSE"
    python3 - "$STEP_CA_SIGN_RESPONSE" "$CERT_DIR/server.crt" <<'PY'
    import json
    import sys

    response_path, cert_path = sys.argv[1:3]
    with open(response_path, encoding="utf-8") as response_file:
        response = json.load(response_file)
    with open(cert_path, "w", encoding="utf-8") as cert_file:
        cert_file.write(response["crt"])
        if response.get("ca"):
            cert_file.write(response["ca"])
    PY
    rm -f "$STEP_CA_PASSWORD_FILE" "$STEP_CA_TOKEN_FILE" "$STEP_CA_CSR_FILE" "$STEP_CA_SIGN_REQUEST" "$STEP_CA_SIGN_RESPONSE"
    trap - EXIT
    unset STEP_CA_PROVISIONER_PASSWORD
    chown ubuntu:ubuntu "$CERT_DIR/server.crt" "$CERT_DIR/server.key"
    chmod 600 "$CERT_DIR/server.key"
    chmod 644 "$CERT_DIR/server.crt"
    # Keep API trust separate from bridge client trust. STEP_CA_API_ROOT may
    # fall back to a public WebPKI root when the Step CA endpoint uses a public
    # serving cert, but bridgectl's mTLS client CA must be the actual Step CA
    # root that issued client certs.
    install -o ubuntu -g ubuntu -m 0644 "$STEP_CA_ROOT" "$CERT_DIR/step-ca-root.crt"

{{- if .StepCAClients}}
    JWT_CLIENT_DIR="/home/ubuntu/.ai-agent-bridge/certs/jwt-clients"
    install -d -o ubuntu -g ubuntu -m 700 "$JWT_CLIENT_DIR"
{{- range .StepCAClients}}
    printf '%s' '{{ b64 .PublicKey }}' | base64 -d > "$JWT_CLIENT_DIR/{{ .Issuer }}.pub"
    chown ubuntu:ubuntu "$JWT_CLIENT_DIR/{{ .Issuer }}.pub"
    chmod 644 "$JWT_CLIENT_DIR/{{ .Issuer }}.pub"
{{- end}}
{{- end}}

    STEP_CA_CLIENTS_JSON_B64="{{ .StepCAClientsJSONB64 }}"
    python3 - /home/ubuntu/.config/bridgectl/config.yaml "$STEP_CA" "$CERT_DIR/step-ca-root.crt" "$CERT_DIR/server.crt" "$CERT_DIR/server.key" "$STEP_CA_CLIENTS_JSON_B64" "$STEP_PROVISIONER" "$STEP_CA_PERSISTENT_PASSWORD_FILE" <<'PY'
    import base64
    import json
    import sys
    import yaml

    config_path, step_ca, root_path, cert_path, key_path, clients_b64, provisioner, provisioner_password_file = sys.argv[1:9]
    with open(config_path, encoding="utf-8") as config_file:
        config = yaml.safe_load(config_file) or {}
    step_ca_config = config.setdefault("step_ca", {})
    step_ca_config["url"] = f"https://{step_ca}"
    step_ca_config["root"] = root_path
    if provisioner:
        step_ca_config["provisioner"] = provisioner
    else:
        step_ca_config.pop("provisioner", None)
    step_ca_config["provisioner_password_file"] = provisioner_password_file
    config["tls"] = {
        "ca_bundle": root_path,
        "cert": cert_path,
        "key": key_path,
    }
    if clients_b64:
        step_ca_config["clients"] = json.loads(base64.b64decode(clients_b64).decode("utf-8"))
    with open(config_path, "w", encoding="utf-8") as config_file:
        yaml.safe_dump(config, config_file, default_flow_style=False, sort_keys=False)
    PY
    chown ubuntu:ubuntu /home/ubuntu/.config/bridgectl/config.yaml
    chmod 600 /home/ubuntu/.config/bridgectl/config.yaml

    {
      printf 'STEP_CA_URL="%s"\n' "https://${STEP_CA}"
      printf 'STEP_CA_PROVISIONER="%s"\n' "$STEP_PROVISIONER"
      printf 'BRIDGECTL_TLS_CERT="%s"\n' "$CERT_DIR/server.crt"
      printf 'BRIDGECTL_TLS_KEY="%s"\n' "$CERT_DIR/server.key"
    } > /home/ubuntu/.config/bridgectl/step-ca.env
    chown ubuntu:ubuntu /home/ubuntu/.config/bridgectl/step-ca.env
    chmod 600 /home/ubuntu/.config/bridgectl/step-ca.env
    )
{{- end}}

{{- if .PackagesPreInstalled}}
  # --- update ballast to latest version ---
  - "sudo -u ubuntu /home/linuxbrew/.linuxbrew/bin/ballast update || echo 'WARNING: ballast update failed'"

  # --- TLS + nginx + /app/ route via ai-desktops-setup-tls ---
  # Reconfigures ports (80→{{ .NoVNCHTTPPort }}, 443→{{ .NoVNCHTTPSPort }}), obtains a
  # Let's Encrypt cert via DNS-01 (Route53), wires it into the novnc nginx
  # config, and adds the /app/ proxy location for the ai-desktops web app.
  - |
    CERTBOT_DOMAIN="{{ .Hostname }}" \
    CERTBOT_EMAIL="{{ .CertbotEmail }}" \
    NOVNC_HTTP_PORT="{{ .NoVNCHTTPPort }}" \
    NOVNC_HTTPS_PORT="{{ .NoVNCHTTPSPort }}" \
    /usr/local/bin/ai-desktops-setup-tls
  - "systemctl enable novnc-desktop 2>/dev/null || echo \"WARNING: novnc-desktop.service not found\""
  - "systemctl start novnc-desktop 2>/dev/null || echo \"WARNING: could not start novnc-desktop\""
{{- else}}
  # --- TLS certificate via Route53 DNS-01 (no port 80 required) ---
  - |
    if command -v certbot &>/dev/null; then
      certbot certonly --dns-route53 --non-interactive --agree-tos --email {{ .CertbotEmail }} -d {{ .Hostname }} || echo "WARNING: certbot failed"
      systemctl enable certbot.timer 2>/dev/null || true
      systemctl start certbot.timer 2>/dev/null || true
    else
      echo "ERROR: certbot not found"
      exit 1
    fi
{{- end}}


  # --- retrieve GitHub credentials and configure SSH ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    SECRET="{{ .GitHubSecretPath }}"
    WORKSPACE="{{ .WorkspacePath }}"
    OWNER="{{ .GitHubOwner }}"

    # Retrieve JSON secret from Secrets Manager
    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$SECRET" \
      --query SecretString \
      --output text)

    if [ -z "$SECRET_JSON" ]; then
      echo "ERROR: could not retrieve secret from $SECRET" >&2
      exit 1
    fi

    GITHUB_TOKEN=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['github_token'])")
    SSH_KEY=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['ssh_private_key'])")
    unset SECRET_JSON

    # Install SSH private key for github.com (ubuntu)
    install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.ssh
    printf '%s\n' "$SSH_KEY" > /home/ubuntu/.ssh/github_ed25519
    chmod 600 /home/ubuntu/.ssh/github_ed25519
    chown ubuntu:ubuntu /home/ubuntu/.ssh/github_ed25519

    # Configure SSH to use the key for github.com (ubuntu)
    printf 'Host github.com\n  IdentityFile ~/.ssh/github_ed25519\n  StrictHostKeyChecking accept-new\n  User git\n' \
      > /home/ubuntu/.ssh/config
    chmod 600 /home/ubuntu/.ssh/config
    chown ubuntu:ubuntu /home/ubuntu/.ssh/config

    # Authenticate gh CLI as ubuntu user without invoking the interactive login flow.
    install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.config/gh
    {
      printf 'github.com:\n'
      printf '    oauth_token: %s\n' "$GITHUB_TOKEN"
      printf '    git_protocol: ssh\n'
      printf '    user: %s\n' "$OWNER"
    } > /home/ubuntu/.config/gh/hosts.yml
    chmod 600 /home/ubuntu/.config/gh/hosts.yml
    chown ubuntu:ubuntu /home/ubuntu/.config/gh/hosts.yml
    sudo -u ubuntu gh auth setup-git --hostname github.com || echo "WARNING: gh auth setup-git failed - gh CLI may not be fully configured"

    # Configure git commit identity (ubuntu)
    sudo -u ubuntu git config --global user.name  "{{ if .GitUserName }}{{ .GitUserName }}{{ else }}AI Desktop ({{ .DesktopID }}){{ end }}"
    sudo -u ubuntu git config --global user.email "{{ if .GitUserEmail }}{{ .GitUserEmail }}{{ else }}desktop-{{ .DesktopID }}@noreply.github.com{{ end }}"
    sudo -u ubuntu git config --global --add safe.directory '*'

    # Write ~/.npmrc so the ubuntu user can install @{{ .GitHubOwner }} packages from GitHub Packages.
    # Pre-create with correct ownership and mode before writing so the token is never world-readable.
    install -o ubuntu -g ubuntu -m 600 /dev/null /home/ubuntu/.npmrc
    printf '@{{ .GitHubOwner }}:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=%s\n' "$GITHUB_TOKEN" \
      > /home/ubuntu/.npmrc

    unset SSH_KEY
    unset GITHUB_TOKEN
    )

{{- if .AgentSecretPath}}
  # --- retrieve AI provider API keys and write bridgectl agents.env ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    AGENT_SECRET="{{ .AgentSecretPath }}"

    # Retrieve JSON secret from Secrets Manager
    AGENT_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$AGENT_SECRET" \
      --query SecretString \
      --output text 2>/dev/null) || { echo "WARNING: could not retrieve agent secret from $AGENT_SECRET" >&2; exit 0; }

    # --output text returns the literal string "None" when SecretString is null
    if [ -z "$AGENT_JSON" ] || [ "$AGENT_JSON" = "None" ]; then
      echo "WARNING: agent secret $AGENT_SECRET was empty — bridgectl agents.env not written" >&2
      exit 0
    fi

    # Write env file to bridgectl config dir (read by systemd user service EnvironmentFile)
    install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.config/bridgectl
    ENV_RENDERER=$(cat <<'PY'
    import json, re, sys
    d = json.load(sys.stdin)
    valid_key = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
    sq = lambda v: chr(39) + str(v).replace(chr(39), chr(39)+chr(92)+chr(39)+chr(39)) + chr(39)
    def normalize(v):
        if isinstance(v, (dict, list)):
            return json.dumps(v, separators=(',', ':'))
        sv = str(v)
        if '\0' in sv:
            return None
        stripped = sv.strip()
        if '\n' in sv and stripped[:1] in ('{', '['):
            try:
                return json.dumps(json.loads(sv), separators=(',', ':'))
            except json.JSONDecodeError:
                return None
        if '\n' in sv:
            return None
        return sv
    for k, v in d.items():
        if not valid_key.match(k):
            print(f'WARNING: skipping agent secret key {k!r} (not a valid env var name)', file=sys.stderr)
            continue
        sv = normalize(v)
        if sv is None:
            print(f'WARNING: skipping agent secret key {k!r} (value contains newline/NUL or invalid JSON)', file=sys.stderr)
            continue
        if sv:
            print(f'{k}={sq(sv)}')
    PY
    )
    if ! printf '%s\n' "$AGENT_JSON" | python3 -c "$ENV_RENDERER" > /home/ubuntu/.config/bridgectl/agents.env; then
      echo "WARNING: failed to parse agent secret JSON — bridgectl agents.env not written" >&2
      exit 0
    fi
    chmod 600 /home/ubuntu/.config/bridgectl/agents.env
    chown ubuntu:ubuntu /home/ubuntu/.config/bridgectl/agents.env
    unset AGENT_JSON
    )
{{- end}}

{{- if .DesktopSecretPaths}}
  # --- retrieve desktop secrets and inject into ubuntu environment ---
  - |
    (
    REGION="{{ .AWSRegion }}"
    DESKTOP_ENV_TMP=$(mktemp)
    trap 'rm -f "$DESKTOP_ENV_TMP"' EXIT
{{ range .DesktopSecretPaths }}
    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "{{ . }}" \
      --query SecretString \
      --output text 2>/dev/null) || true
    if [ -z "$SECRET_JSON" ] || [ "$SECRET_JSON" = "None" ]; then
      echo "WARNING: could not retrieve desktop secret {{ . }}" >&2
    else
      ENV_RENDERER=$(cat <<'PY'
    import json, re, sys
    d = json.load(sys.stdin)
    valid_key = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
    sq = lambda v: chr(39)+str(v).replace(chr(39), chr(39)+chr(92)+chr(39)+chr(39))+chr(39)
    def normalize(v):
        if isinstance(v, (dict, list)):
            return json.dumps(v, separators=(',', ':'))
        sv = str(v)
        if '\0' in sv:
            return None
        stripped = sv.strip()
        if '\n' in sv and stripped[:1] in ('{', '['):
            try:
                return json.dumps(json.loads(sv), separators=(',', ':'))
            except json.JSONDecodeError:
                return None
        if '\n' in sv:
            return None
        return sv
    for k, v in d.items():
        if not valid_key.match(k):
            print(f'WARNING: skipping secret key {k!r} (not a valid env var name)', file=sys.stderr)
            continue
        sv = normalize(v)
        if sv is None:
            print(f'WARNING: skipping secret key {k!r} (value contains newline/NUL or invalid JSON)', file=sys.stderr)
            continue
        if sv:
            print(f'{k}={sq(sv)}')
    PY
      )
      printf '%s\n' "$SECRET_JSON" | python3 -c "$ENV_RENDERER" >> "$DESKTOP_ENV_TMP" || echo "WARNING: failed to parse desktop secret {{ . }}" >&2
    fi
    unset SECRET_JSON
{{ end }}
    if [ -s "$DESKTOP_ENV_TMP" ]; then
      # systemd user environment (read by user manager; available to bridgectl and other user services)
      install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.config/environment.d
      install -o ubuntu -g ubuntu -m 600 "$DESKTOP_ENV_TMP" \
        /home/ubuntu/.config/environment.d/desktop-secrets.conf
      chown ubuntu:ubuntu /home/ubuntu/.config/environment.d/desktop-secrets.conf

      # shell-sourceable file for interactive sessions
      install -o ubuntu -g ubuntu -m 600 /dev/null /home/ubuntu/.desktop-secrets
      while IFS= read -r kv; do
        printf 'export %s\n' "$kv" >> /home/ubuntu/.desktop-secrets
      done < "$DESKTOP_ENV_TMP"
      chown ubuntu:ubuntu /home/ubuntu/.desktop-secrets

      # source from .bashrc if not already wired
      if ! grep -qF '.desktop-secrets' /home/ubuntu/.bashrc 2>/dev/null; then
        printf '\n[ -f ~/.desktop-secrets ] && . ~/.desktop-secrets\n' >> /home/ubuntu/.bashrc
      fi
    fi
    )
{{- end}}

  # --- suppress Claude Code first-run onboarding (blocks non-interactive use) ---
  - |
    if [ ! -f /home/ubuntu/.claude.json ]; then
      printf '{\n  "hasCompletedOnboarding": true\n}\n' > /home/ubuntu/.claude.json
      chown ubuntu:ubuntu /home/ubuntu/.claude.json
      chmod 600 /home/ubuntu/.claude.json
    fi

  # --- clone repositories ---
{{ range .Repos }}
  - |
    (
    set -e
    OWNER="{{ $.GitHubOwner }}"
    WORKSPACE="{{ $.WorkspacePath }}"
    REPO_URL="{{ . }}"
    REPO_NAME=$(basename "$REPO_URL" .git)
    REPO_OWNER=$(echo "$REPO_URL" | sed 's|.*github\.com[/:]||' | cut -d/ -f1)

    if [ "$REPO_OWNER" != "$OWNER" ]; then
      echo "ERROR: repo $REPO_URL owner $REPO_OWNER does not match desktop owner $OWNER" >&2
      exit 1
    fi

    DEST="$WORKSPACE/$REPO_NAME"
    if [ ! -d "$DEST/.git" ]; then
      sudo -u ubuntu git clone "git@github.com:${OWNER}/${REPO_NAME}.git" "$DEST"
    fi
    )
{{ end }}

  # --- enable and start bridgectl user service ---
  - |
    (
    set -e
    UBUNTU_UID=$(id -u ubuntu)
{{- if .Repos}}
    # Set working directory to first repo workspace
    FIRST_REPO_NAME=$(basename "{{ index .Repos 0 }}" .git)
    WORKING_DIR="{{ .WorkspacePath }}/$FIRST_REPO_NAME"
{{- else}}
    WORKING_DIR="{{ .WorkspacePath }}"
{{- end}}
    # Write drop-in to set the actual working directory for the service
    install -d -o ubuntu -g ubuntu -m 755 /home/ubuntu/.config/systemd/user/bridgectl.service.d
    printf '[Service]\nWorkingDirectory=%s\n' "$WORKING_DIR" \
      > /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf
    chown ubuntu:ubuntu /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf
    chmod 644 /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf

{{- if .StepCAServerDNS}}
    # Make step-ca metadata and issued certificate paths available to bridgectl.
    printf '[Service]\nEnvironmentFile=-%%h/.config/bridgectl/step-ca.env\n' \
      > /home/ubuntu/.config/systemd/user/bridgectl.service.d/step-ca.conf
    chown ubuntu:ubuntu /home/ubuntu/.config/systemd/user/bridgectl.service.d/step-ca.conf
    chmod 644 /home/ubuntu/.config/systemd/user/bridgectl.service.d/step-ca.conf
{{- end}}

{{- if and .TailscaleNetwork .StepCAServerDNS}}
    # Expose bridgectl only on the Tailscale address when TLS certs are issued.
    TAILSCALE_IP=$(tailscale ip -4 | head -n 1)
    if [ -z "$TAILSCALE_IP" ]; then
      echo "ERROR: Tailscale IPv4 address not available for bridgectl listener" >&2
      exit 1
    fi
    python3 - /home/ubuntu/.config/bridgectl/config.yaml "$TAILSCALE_IP:{{ .BridgePort }}" <<'PY'
    import sys
    import yaml

    path, listen = sys.argv[1:3]
    with open(path, encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}
    server = config.setdefault("server", {})
    server["listen"] = listen
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config, f, default_flow_style=False, sort_keys=False)
    PY
    chown ubuntu:ubuntu /home/ubuntu/.config/bridgectl/config.yaml
    chmod 600 /home/ubuntu/.config/bridgectl/config.yaml
{{- end}}

    # Ensure linger is enabled (may not persist to cloud-init phase from AMI)
    loginctl enable-linger ubuntu 2>/dev/null || true

    # Ensure XDG_RUNTIME_DIR exists (created by systemd at login; may be absent in cloud-init)
    mkdir -p /run/user/$UBUNTU_UID
    chown ubuntu:ubuntu /run/user/$UBUNTU_UID
    chmod 700 /run/user/$UBUNTU_UID

    export UBUNTU_UID
    # Start the user manager so the user bus is available in cloud-init (non-fatal)
    systemctl start user@${UBUNTU_UID}.service 2>/dev/null || true
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user daemon-reload || echo "WARNING: daemon-reload failed; user bus may not be ready yet"
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user enable bridgectl || echo "WARNING: bridgectl enable failed; it will be enabled at next login"
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user start bridgectl || echo "WARNING: bridgectl user service failed to start; it will start at next login"
    )

{{- if gt .SwapSizeGB 0}}
  # --- swap file (prevents OOM crashes under memory pressure) ---
  - |
    (
    set -e
    SWAP_SIZE_GB="{{ .SwapSizeGB }}"
    SWAP_FILE="/swapfile"
    if [ -f "$SWAP_FILE" ]; then
      echo "Swap file $SWAP_FILE already exists; ensuring it is active"
    else
      fallocate -l "${SWAP_SIZE_GB}G" "$SWAP_FILE" || dd if=/dev/zero of="$SWAP_FILE" bs=1G count="$SWAP_SIZE_GB"
      chmod 600 "$SWAP_FILE"
      mkswap "$SWAP_FILE"
      echo "Swap file ${SWAP_SIZE_GB}G created"
    fi
    # Activate swap if not already on (idempotent)
    if ! swapon --show --noheadings | grep -q "^${SWAP_FILE}"; then
      swapon "$SWAP_FILE"
      echo "Swap activated"
    fi
    # Ensure fstab entry exists (idempotent)
    if ! grep -qF "${SWAP_FILE} none swap" /etc/fstab; then
      echo "${SWAP_FILE} none swap sw 0 0" >> /etc/fstab
    fi
    # Reduce swappiness: prefer RAM, use swap only under real pressure
    echo 'vm.swappiness=10' > /etc/sysctl.d/99-ai-desktops.conf
    sysctl -p /etc/sysctl.d/99-ai-desktops.conf
    )
{{- end}}

  # --- CloudWatch agent: memory/disk metrics and system log forwarding ---
  - |
    (
    DESKTOP_ID="{{ .DesktopID }}"
    AWS_REGION="{{ .AWSRegion }}"

    # Install agent if not already present (pre-baked AMIs may include it)
    if ! [ -f /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent ]; then
      CW_ARCH=$(dpkg --print-architecture)
      wget -q --timeout=60 --tries=3 \
        "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/${CW_ARCH}/latest/amazon-cloudwatch-agent.deb" \
        -O /tmp/amazon-cloudwatch-agent.deb \
        && /opt/ai-desktops/apt-with-lock dpkg -i /tmp/amazon-cloudwatch-agent.deb \
        && rm -f /tmp/amazon-cloudwatch-agent.deb \
        || echo "WARNING: CloudWatch agent download/install failed; metrics will not be collected"
    fi

    if ! [ -f /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent ]; then
      echo "WARNING: CloudWatch agent not available; skipping configuration"
    else
      mkdir -p /opt/aws/amazon-cloudwatch-agent/etc
      python3 -c "
    import json, sys
    config = {
      'agent': {
        'metrics_collection_interval': 60,
        'region': '$AWS_REGION'
      },
      'metrics': {
        'namespace': 'ai-desktops',
        'append_dimensions': {
          'DesktopId': '$DESKTOP_ID'
        },
        'metrics_collected': {
          'mem': {
            'measurement': ['mem_used_percent', 'mem_used', 'mem_available', 'mem_total'],
            'metrics_collection_interval': 60
          },
          'disk': {
            'measurement': ['disk_used_percent', 'disk_used', 'disk_free'],
            'metrics_collection_interval': 60,
            'resources': ['/']
          },
          'swap': {
            'measurement': ['swap_used_percent', 'swap_used', 'swap_free'],
            'metrics_collection_interval': 60
          }
        }
      },
      'logs': {
        'logs_collected': {
          'files': {
            'collect_list': [
              {
                'file_path': '/var/log/syslog',
                'log_group_name': '/ai-desktops/syslog',
                'log_stream_name': '{instance_id}',
                'retention_in_days': 14
              },
              {
                'file_path': '/var/log/cloud-init-output.log',
                'log_group_name': '/ai-desktops/cloud-init',
                'log_stream_name': '{instance_id}',
                'retention_in_days': 14
              }
            ]
          }
        }
      }
    }
    print(json.dumps(config, indent=2))
    " > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

      /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
        -a fetch-config \
        -m ec2 \
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
        -s \
        || echo "WARNING: CloudWatch agent failed to start; metrics will not be collected"
    fi
    )

{{- if .AVDsJSONB64}}
  # --- provision Android Virtual Devices via Ansible ---
  - |
    if [ ! -f /opt/ai-desktops/desktop-setup.yml ]; then
      echo "WARNING: /opt/ai-desktops/desktop-setup.yml not found — skipping AVD provisioning"
    elif ! command -v ansible-playbook >/dev/null 2>&1; then
      echo "WARNING: ansible-playbook not found — skipping AVD provisioning"
    else
      echo '{{ .AVDsJSONB64 }}' | base64 -d > /tmp/avd-vars.json
      ansible-playbook /opt/ai-desktops/desktop-setup.yml \
        --connection local \
        --inventory localhost, \
        --extra-vars @/tmp/avd-vars.json \
        || echo "WARNING: AVD provisioning failed — check /var/log/cloud-init-output.log"
      rm -f /tmp/avd-vars.json
    fi
{{- end}}

  # --- write desktop metadata ---
  - |
    {
      printf 'DESKTOP_ID="%s"\n' "{{ .DesktopID }}"
      printf 'GITHUB_OWNER="%s"\n' "{{ .GitHubOwner }}"
      printf 'WORKSPACE="%s"\n' "{{ .WorkspacePath }}"
      printf 'ENVIRONMENT="%s"\n' "{{ .Environment }}"
      printf 'BRIDGE_PORT="%s"\n' "{{ .BridgePort }}"
{{- if .TailscaleNetwork}}
      printf 'TAILSCALE_NETWORK="%s"\n' "{{ .TailscaleNetwork }}"
{{- end}}
{{- if .StepCAServerDNS}}
      printf 'STEP_CA_URL="%s"\n' "https://{{ .StepCAServerDNS }}"
      printf 'STEP_CA_PROVISIONER="%s"\n' "{{ .StepCAProvisioner }}"
{{- end}}
    } > /opt/ai-desktops/desktop.env
    chgrp ubuntu /opt/ai-desktops/desktop.env
    chmod 640 /opt/ai-desktops/desktop.env

final_message: "ai-desktops bootstrap complete for {{ .DesktopID }}"
`

// RenderCloudInit renders the cloud-init user-data for the given config.
func RenderCloudInit(cfg *BootstrapConfig) (string, error) {
	if cfg.WorkspacePath == "" {
		cfg.WorkspacePath = "/workspace"
	}
	if cfg.BridgePort == 0 {
		cfg.BridgePort = 9445
	}
	if cfg.NoVNCHTTPPort == 0 {
		cfg.NoVNCHTTPPort = DefaultNoVNCHTTPPort
	}
	if cfg.NoVNCHTTPSPort == 0 {
		cfg.NoVNCHTTPSPort = DefaultNoVNCHTTPSPort
	}
	if cfg.CertbotEmail == "" {
		cfg.CertbotEmail = "admin@orchael.ai"
	}

	// Pre-compute AVD vars JSON (base64-encoded) for safe shell embedding in cloud-init.
	// Base64 avoids heredoc indentation issues and shell quote escaping.
	var avdsJSONB64 string
	if len(cfg.AVDs) > 0 {
		type avdVar struct {
			Name   string `json:"name"`
			Image  string `json:"image"`
			Device string `json:"device,omitempty"`
		}
		vars := struct {
			AVDs []avdVar `json:"avds"`
		}{}
		for _, a := range cfg.AVDs {
			vars.AVDs = append(vars.AVDs, avdVar{Name: a.Name, Image: a.Image, Device: a.Device})
		}
		b, err := json.Marshal(vars)
		if err != nil {
			return "", err
		}
		avdsJSONB64 = base64.StdEncoding.EncodeToString(b)
	}
	var stepCAClientsJSONB64 string
	if len(cfg.StepCAClients) > 0 {
		type clientVar struct {
			Issuer   string `json:"issuer"`
			KeyPath  string `json:"key_path"`
			Required bool   `json:"required,omitempty"`
		}
		clients := make([]clientVar, 0, len(cfg.StepCAClients))
		for _, c := range cfg.StepCAClients {
			clients = append(clients, clientVar{
				Issuer:   c.Issuer,
				KeyPath:  "/home/ubuntu/.ai-agent-bridge/certs/jwt-clients/" + c.Issuer + ".pub",
				Required: c.Required,
			})
		}
		b, err := json.Marshal(clients)
		if err != nil {
			return "", err
		}
		stepCAClientsJSONB64 = base64.StdEncoding.EncodeToString(b)
	}

	// Expose version constants and pre-computed fields to the template via a wrapper.
	type templateData struct {
		*BootstrapConfig
		BridgeVersion        string
		BridgePackageVersion string
		AVDsJSONB64          string
		StepCAClientsJSONB64 string
	}
	data := templateData{
		BootstrapConfig:      cfg,
		BridgeVersion:        AIAgentBridgeVersion,
		BridgePackageVersion: strings.TrimPrefix(AIAgentBridgeVersion, "v"),
		AVDsJSONB64:          avdsJSONB64,
		StepCAClientsJSONB64: stepCAClientsJSONB64,
	}

	funcMap := template.FuncMap{
		"b64": func(text string) string {
			return base64.StdEncoding.EncodeToString([]byte(text))
		},
		"indent": func(spaces int, text string) string {
			lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
			indent := strings.Repeat(" ", spaces)
			for i, line := range lines {
				if line != "" {
					lines[i] = indent + line
				}
			}
			return strings.Join(lines, "\n")
		},
	}
	tmpl, err := template.New("cloud-init").Funcs(funcMap).Parse(cloudInitTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
