package provision

import (
	"bytes"
	"text/template"
)

// BootstrapConfig holds the parameters for rendering the cloud-init user-data.
type BootstrapConfig struct {
	DesktopID     string
	GitHubOwner   string
	Repos         []string
	WorkspacePath string
	BridgePort    int
	PATSecretPath string
	AWSRegion     string
	Environment   string
}

const cloudInitTemplate = `#cloud-config
# ai-desktops bootstrap — desktop {{ .DesktopID }}
# Generated by ai-desktops CLI

package_update: true
package_upgrade: false

packages:
  - git
  - docker.io
  - tmux
  - curl
  - wget
  - unzip
  - ca-certificates
  - apt-transport-https
  - gnupg
  - lsb-release
  - software-properties-common
  - snapd

runcmd:
  # --- system setup ---
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

  # --- nvim (via snap) ---
  - snap install nvim --classic

  # --- workspace ---
  - mkdir -p {{ .WorkspacePath }}
  - chown ubuntu:ubuntu {{ .WorkspacePath }}

  # --- ai-desktops runtime directory ---
  - mkdir -p /opt/ai-desktops
  - chown ubuntu:ubuntu /opt/ai-desktops

  # --- novnc-desktop ---
  - curl -fsSL https://raw.githubusercontent.com/orchael/novnc-desktop/main/install.sh | bash -s -- --desktop-type elementary

  # --- ai-agent-bridge ---
  - curl -fsSL https://raw.githubusercontent.com/orchael/ai-agent-bridge/main/install.sh | bash -s -- --bind 127.0.0.1 --port {{ .BridgePort }}
  - systemctl enable ai-agent-bridge
  - systemctl start ai-agent-bridge

  # --- retrieve github PAT and clone repos ---
  - |
    set -e
    REGION="{{ .AWSRegion }}"
    PAT_SECRET="{{ .PATSecretPath }}"
    WORKSPACE="{{ .WorkspacePath }}"
    OWNER="{{ .GitHubOwner }}"

    # Retrieve PAT from AWS Secrets Manager
    PAT=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$PAT_SECRET" \
      --query SecretString \
      --output text 2>/dev/null) || \
    PAT=$(aws ssm get-parameter \
      --region "$REGION" \
      --name "$PAT_SECRET" \
      --with-decryption \
      --query Parameter.Value \
      --output text)

    # Validate PAT was retrieved
    if [ -z "$PAT" ]; then
      echo "ERROR: could not retrieve GitHub PAT from $PAT_SECRET" >&2
      exit 1
    fi

    # Clone repositories
{{ range .Repos }}
    REPO_URL="{{ . }}"
    REPO_NAME=$(basename "$REPO_URL" .git)
    REPO_OWNER=$(echo "$REPO_URL" | sed 's|.*github.com/||' | cut -d/ -f1)

    # Enforce owner boundary
    if [ "$REPO_OWNER" != "$OWNER" ]; then
      echo "ERROR: repo $REPO_URL owner $REPO_OWNER does not match desktop owner $OWNER" >&2
      exit 1
    fi

    DEST="$WORKSPACE/$REPO_NAME"
    if [ ! -d "$DEST/.git" ]; then
      git clone "https://x-access-token:${PAT}@github.com/${OWNER}/${REPO_NAME}.git" "$DEST"
      chown -R ubuntu:ubuntu "$DEST"
    fi
{{ end }}
    # Clear PAT from environment
    unset PAT

  # --- write desktop metadata ---
  - |
    cat > /opt/ai-desktops/desktop.env << 'ENVEOF'
    DESKTOP_ID="{{ .DesktopID }}"
    GITHUB_OWNER="{{ .GitHubOwner }}"
    WORKSPACE="{{ .WorkspacePath }}"
    ENVIRONMENT="{{ .Environment }}"
    BRIDGE_PORT="{{ .BridgePort }}"
ENVEOF
    chmod 600 /opt/ai-desktops/desktop.env

final_message: "ai-desktops bootstrap complete for {{ .DesktopID }}"
`

// RenderCloudInit renders the cloud-init user-data for the given config.
func RenderCloudInit(cfg *BootstrapConfig) (string, error) {
	if cfg.WorkspacePath == "" {
		cfg.WorkspacePath = "/workspace"
	}
	if cfg.BridgePort == 0 {
		cfg.BridgePort = 9445
	}

	tmpl, err := template.New("cloud-init").Parse(cloudInitTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", err
	}
	return buf.String(), nil
}
