package provision

import (
	"bytes"
	"strings"
	"text/template"
)

const (
	// AIAgentBridgeVersion must match ai_agent_bridge_version in packer/variables.pkrvars.hcl.
	AIAgentBridgeVersion  = "v0.7.4"
	DefaultNoVNCHTTPPort  = 8080
	DefaultNoVNCHTTPSPort = 8443
)

// BootstrapConfig holds the parameters for rendering the cloud-init user-data.
type BootstrapConfig struct {
	DesktopID            string
	Hostname             string // FQDN used for certbot cert and novnc-desktop cert path
	GitHubOwner          string
	Repos                []string
	WorkspacePath        string
	BridgePort           int
	NoVNCHTTPPort        int
	NoVNCHTTPSPort       int
	CertbotEmail         string
	GitHubSecretPath     string   // AWS Secrets Manager path: /ai-desktops/<owner>/github
	AgentSecretPath      string   // AWS Secrets Manager path: /ai-desktops/<owner>/agents
	DesktopSecretPaths   []string // additional AWS Secrets Manager paths whose JSON keys become ubuntu env vars
	AWSRegion            string
	Environment          string
	PackagesPreInstalled bool
	SSHPublicKey         string // ed25519/RSA public key injected into ubuntu's authorized_keys
	GitUserName          string // git config user.name written to ubuntu's global git config
	GitUserEmail         string // git config user.email written to ubuntu's global git config

}

const cloudInitTemplate = `#cloud-config
# ai-desktops bootstrap — desktop {{ .DesktopID }}
# Generated by ai-desktops CLI
{{- if .SSHPublicKey}}

ssh_authorized_keys:
  - {{ .SSHPublicKey }}
{{- end}}

{{- if not .PackagesPreInstalled}}
package_update: true
package_upgrade: false

packages:
  - git
  - docker.io
  - tmux
  - curl
  - wget
  - unzip
  - ca-certificates
  - apt-transport-https
  - gnupg
  - lsb-release
  - software-properties-common
  - snapd
  - awscli
  - certbot
  - python3-certbot-dns-route53
  - ansible
  - gh
{{- end}}

runcmd:
  # --- system setup ---
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

{{- if not .PackagesPreInstalled}}
  # --- nvim (via snap) ---
  - snap install nvim --classic
{{- end}}

  # --- workspace ---
  - mkdir -p {{ .WorkspacePath }}
  - chown ubuntu:ubuntu {{ .WorkspacePath }}

  # --- ai-desktops runtime directory ---
  - mkdir -p /opt/ai-desktops
  - chown ubuntu:ubuntu /opt/ai-desktops

{{- if .PackagesPreInstalled}}
  # --- TLS + nginx + /app/ route via ai-desktops-setup-tls ---
  # Reconfigures ports (80→{{ .NoVNCHTTPPort }}, 443→{{ .NoVNCHTTPSPort }}), obtains a
  # Let's Encrypt cert via DNS-01 (Route53), wires it into the novnc nginx
  # config, and adds the /app/ proxy location for the ai-desktops web app.
  - |
    CERTBOT_DOMAIN="{{ .Hostname }}" \
    CERTBOT_EMAIL="{{ .CertbotEmail }}" \
    NOVNC_HTTP_PORT="{{ .NoVNCHTTPPort }}" \
    NOVNC_HTTPS_PORT="{{ .NoVNCHTTPSPort }}" \
    /usr/local/bin/ai-desktops-setup-tls
  - "systemctl enable novnc-desktop 2>/dev/null || echo \"WARNING: novnc-desktop.service not found\""
  - "systemctl start novnc-desktop 2>/dev/null || echo \"WARNING: could not start novnc-desktop\""
{{- else}}
  # --- TLS certificate via Route53 DNS-01 (no port 80 required) ---
  - |
    if command -v certbot &>/dev/null; then
      certbot certonly --dns-route53 --non-interactive --agree-tos --email {{ .CertbotEmail }} -d {{ .Hostname }} || echo "WARNING: certbot failed"
      systemctl enable certbot.timer 2>/dev/null || true
      systemctl start certbot.timer 2>/dev/null || true
    else
      echo "ERROR: certbot not found"
      exit 1
    fi
{{- end}}


  # --- retrieve GitHub credentials and configure SSH ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    SECRET="{{ .GitHubSecretPath }}"
    WORKSPACE="{{ .WorkspacePath }}"
    OWNER="{{ .GitHubOwner }}"

    # Retrieve JSON secret from Secrets Manager
    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$SECRET" \
      --query SecretString \
      --output text)

    if [ -z "$SECRET_JSON" ]; then
      echo "ERROR: could not retrieve secret from $SECRET" >&2
      exit 1
    fi

    GITHUB_TOKEN=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['github_token'])")
    SSH_KEY=$(printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['ssh_private_key'])")
    unset SECRET_JSON

    # Install SSH private key for github.com (ubuntu)
    install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.ssh
    printf '%s\n' "$SSH_KEY" > /home/ubuntu/.ssh/github_ed25519
    chmod 600 /home/ubuntu/.ssh/github_ed25519
    chown ubuntu:ubuntu /home/ubuntu/.ssh/github_ed25519

    # Configure SSH to use the key for github.com (ubuntu)
    printf 'Host github.com\n  IdentityFile ~/.ssh/github_ed25519\n  StrictHostKeyChecking accept-new\n  User git\n' \
      > /home/ubuntu/.ssh/config
    chmod 600 /home/ubuntu/.ssh/config
    chown ubuntu:ubuntu /home/ubuntu/.ssh/config

    # Authenticate gh CLI as ubuntu user (non-fatal: token may lack read:org scope)
    printf '%s\n' "$GITHUB_TOKEN" | sudo -u ubuntu gh auth login --with-token || echo "WARNING: gh auth login failed - gh CLI may not be fully authenticated"

    # Configure git commit identity (ubuntu)
    sudo -u ubuntu git config --global user.name  "{{ if .GitUserName }}{{ .GitUserName }}{{ else }}AI Desktop ({{ .DesktopID }}){{ end }}"
    sudo -u ubuntu git config --global user.email "{{ if .GitUserEmail }}{{ .GitUserEmail }}{{ else }}desktop-{{ .DesktopID }}@noreply.github.com{{ end }}"
    sudo -u ubuntu git config --global --add safe.directory '*'

    # Write ~/.npmrc so the ubuntu user can install @{{ .GitHubOwner }} packages from GitHub Packages.
    # Pre-create with correct ownership and mode before writing so the token is never world-readable.
    install -o ubuntu -g ubuntu -m 600 /dev/null /home/ubuntu/.npmrc
    printf '@{{ .GitHubOwner }}:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=%s\n' "$GITHUB_TOKEN" \
      > /home/ubuntu/.npmrc

    unset SSH_KEY
    unset GITHUB_TOKEN
    )

{{- if .AgentSecretPath}}
  # --- retrieve AI provider API keys and write bridgectl agents.env ---
  - |
    (
    set -e
    REGION="{{ .AWSRegion }}"
    AGENT_SECRET="{{ .AgentSecretPath }}"

    # Retrieve JSON secret from Secrets Manager
    AGENT_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "$AGENT_SECRET" \
      --query SecretString \
      --output text 2>/dev/null) || { echo "WARNING: could not retrieve agent secret from $AGENT_SECRET" >&2; exit 0; }

    # --output text returns the literal string "None" when SecretString is null
    if [ -z "$AGENT_JSON" ] || [ "$AGENT_JSON" = "None" ]; then
      echo "WARNING: agent secret $AGENT_SECRET was empty — bridgectl agents.env not written" >&2
      exit 0
    fi

    # Write env file to bridgectl config dir (read by systemd user service EnvironmentFile)
    install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.config/bridgectl
    if ! printf '%s\n' "$AGENT_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print('\n'.join(f'{k}={v}' for k,v in d.items() if v))" > /home/ubuntu/.config/bridgectl/agents.env; then
      echo "WARNING: failed to parse agent secret JSON — bridgectl agents.env not written" >&2
      exit 0
    fi
    chmod 600 /home/ubuntu/.config/bridgectl/agents.env
    chown ubuntu:ubuntu /home/ubuntu/.config/bridgectl/agents.env
    unset AGENT_JSON
    )
{{- end}}

{{- if .DesktopSecretPaths}}
  # --- retrieve desktop secrets and inject into ubuntu environment ---
  - |
    (
    REGION="{{ .AWSRegion }}"
    DESKTOP_ENV_TMP=$(mktemp)
    trap 'rm -f "$DESKTOP_ENV_TMP"' EXIT
{{ range .DesktopSecretPaths }}
    SECRET_JSON=$(aws secretsmanager get-secret-value \
      --region "$REGION" \
      --secret-id "{{ . }}" \
      --query SecretString \
      --output text 2>/dev/null) || true
    if [ -z "$SECRET_JSON" ] || [ "$SECRET_JSON" = "None" ]; then
      echo "WARNING: could not retrieve desktop secret {{ . }}" >&2
    else
      printf '%s\n' "$SECRET_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); sq=lambda v: chr(39)+str(v).replace(chr(39), chr(39)+chr(92)+chr(39)+chr(39))+chr(39); print('\n'.join(f'{k}={sq(v)}' for k,v in d.items() if v))" >> "$DESKTOP_ENV_TMP" || echo "WARNING: failed to parse desktop secret {{ . }}" >&2
    fi
    unset SECRET_JSON
{{ end }}
    if [ -s "$DESKTOP_ENV_TMP" ]; then
      # systemd user environment (read by user manager; available to bridgectl and other user services)
      install -d -o ubuntu -g ubuntu -m 700 /home/ubuntu/.config/environment.d
      install -o ubuntu -g ubuntu -m 600 "$DESKTOP_ENV_TMP" \
        /home/ubuntu/.config/environment.d/desktop-secrets.conf
      chown ubuntu:ubuntu /home/ubuntu/.config/environment.d/desktop-secrets.conf

      # shell-sourceable file for interactive sessions
      install -o ubuntu -g ubuntu -m 600 /dev/null /home/ubuntu/.desktop-secrets
      while IFS= read -r kv; do
        printf 'export %s\n' "$kv" >> /home/ubuntu/.desktop-secrets
      done < "$DESKTOP_ENV_TMP"
      chown ubuntu:ubuntu /home/ubuntu/.desktop-secrets

      # source from .bashrc if not already wired
      if ! grep -qF '.desktop-secrets' /home/ubuntu/.bashrc 2>/dev/null; then
        printf '\n[ -f ~/.desktop-secrets ] && . ~/.desktop-secrets\n' >> /home/ubuntu/.bashrc
      fi
    fi
    )
{{- end}}

  # --- suppress Claude Code first-run onboarding (blocks non-interactive use) ---
  - |
    if [ ! -f /home/ubuntu/.claude.json ]; then
      printf '{\n  "hasCompletedOnboarding": true\n}\n' > /home/ubuntu/.claude.json
      chown ubuntu:ubuntu /home/ubuntu/.claude.json
      chmod 600 /home/ubuntu/.claude.json
    fi

  # --- clone repositories ---
{{ range .Repos }}
  - |
    (
    set -e
    OWNER="{{ $.GitHubOwner }}"
    WORKSPACE="{{ $.WorkspacePath }}"
    REPO_URL="{{ . }}"
    REPO_NAME=$(basename "$REPO_URL" .git)
    REPO_OWNER=$(echo "$REPO_URL" | sed 's|.*github\.com[/:]||' | cut -d/ -f1)

    if [ "$REPO_OWNER" != "$OWNER" ]; then
      echo "ERROR: repo $REPO_URL owner $REPO_OWNER does not match desktop owner $OWNER" >&2
      exit 1
    fi

    DEST="$WORKSPACE/$REPO_NAME"
    if [ ! -d "$DEST/.git" ]; then
      sudo -u ubuntu git clone "git@github.com:${OWNER}/${REPO_NAME}.git" "$DEST"
    fi
    )
{{ end }}

  # --- enable and start bridgectl user service ---
  - |
    (
    set -e
    UBUNTU_UID=$(id -u ubuntu)
{{- if .Repos}}
    # Set working directory to first repo workspace
    FIRST_REPO_NAME=$(basename "{{ index .Repos 0 }}" .git)
    WORKING_DIR="{{ .WorkspacePath }}/$FIRST_REPO_NAME"
{{- else}}
    WORKING_DIR="{{ .WorkspacePath }}"
{{- end}}
    # Write drop-in to set the actual working directory for the service
    install -d -o ubuntu -g ubuntu -m 755 /home/ubuntu/.config/systemd/user/bridgectl.service.d
    printf '[Service]\nWorkingDirectory=%s\n' "$WORKING_DIR" \
      > /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf
    chown ubuntu:ubuntu /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf
    chmod 644 /home/ubuntu/.config/systemd/user/bridgectl.service.d/workdir.conf

    # Ensure linger is enabled (may not persist to cloud-init phase from AMI)
    loginctl enable-linger ubuntu 2>/dev/null || true

    # Ensure XDG_RUNTIME_DIR exists (created by systemd at login; may be absent in cloud-init)
    mkdir -p /run/user/$UBUNTU_UID
    chown ubuntu:ubuntu /run/user/$UBUNTU_UID
    chmod 700 /run/user/$UBUNTU_UID

    export UBUNTU_UID
    # Start the user manager so the user bus is available in cloud-init (non-fatal)
    systemctl start user@${UBUNTU_UID}.service 2>/dev/null || true
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user daemon-reload || echo "WARNING: daemon-reload failed; user bus may not be ready yet"
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user enable bridgectl || echo "WARNING: bridgectl enable failed; it will be enabled at next login"
    sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/${UBUNTU_UID} systemctl --user start bridgectl || echo "WARNING: bridgectl user service failed to start; it will start at next login"
    )

  # --- write desktop metadata ---
  - |
    {
      printf 'DESKTOP_ID="%s"\n' "{{ .DesktopID }}"
      printf 'GITHUB_OWNER="%s"\n' "{{ .GitHubOwner }}"
      printf 'WORKSPACE="%s"\n' "{{ .WorkspacePath }}"
      printf 'ENVIRONMENT="%s"\n' "{{ .Environment }}"
      printf 'BRIDGE_PORT="%s"\n' "{{ .BridgePort }}"
    } > /opt/ai-desktops/desktop.env
    chgrp ubuntu /opt/ai-desktops/desktop.env
    chmod 640 /opt/ai-desktops/desktop.env

final_message: "ai-desktops bootstrap complete for {{ .DesktopID }}"
`

// RenderCloudInit renders the cloud-init user-data for the given config.
func RenderCloudInit(cfg *BootstrapConfig) (string, error) {
	if cfg.WorkspacePath == "" {
		cfg.WorkspacePath = "/workspace"
	}
	if cfg.BridgePort == 0 {
		cfg.BridgePort = 9445
	}
	if cfg.NoVNCHTTPPort == 0 {
		cfg.NoVNCHTTPPort = DefaultNoVNCHTTPPort
	}
	if cfg.NoVNCHTTPSPort == 0 {
		cfg.NoVNCHTTPSPort = DefaultNoVNCHTTPSPort
	}
	if cfg.CertbotEmail == "" {
		cfg.CertbotEmail = "admin@orchael.ai"
	}

	// Expose version constants to the template via a wrapper.
	type templateData struct {
		*BootstrapConfig
		BridgeVersion string
	}
	data := templateData{
		BootstrapConfig: cfg,
		BridgeVersion:   AIAgentBridgeVersion,
	}

	funcMap := template.FuncMap{
		"indent": func(spaces int, text string) string {
			lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
			indent := strings.Repeat(" ", spaces)
			for i, line := range lines {
				if line != "" {
					lines[i] = indent + line
				}
			}
			return strings.Join(lines, "\n")
		},
	}
	tmpl, err := template.New("cloud-init").Funcs(funcMap).Parse(cloudInitTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
